spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:54321/client-product-db
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082